// src/pages/TwoFactorAuthPage.jsx
import '../otherStyles/TwoFactorAuthPage.css';

function TwoFactorAuthPage() {
    return (
        <div className="two-factor-auth-page">
             <h1 className="two-factor-title">Two-Factor Authentication (2FA)</h1>
            <div className="two-factor-content">
                <section className="two-factor-section">
                    <h2 className="two-factor-section-title">What is 2FA?</h2>
                     <p>
                        Two-Factor Authentication (2FA), also known as multi-factor authentication, adds an extra layer of security to your online accounts. It requires not only your password but also a second verification method, making it significantly harder for hackers to access your accounts.
                     </p>
                 </section>
                 <section className="two-factor-section">
                       <h2 className="two-factor-section-title">How Does 2FA Work?</h2>
                     <p>
                         Typically, 2FA involves providing your password (first factor) and then providing a code generated by an app, a code sent to your phone via SMS, or a physical security key (second factor). This ensures that even if your password is compromised, your account remains protected since the hacker will need the second factor.
                     </p>
                </section>
                   <section className="two-factor-section">
                       <h2 className="two-factor-section-title">Benefits of 2FA</h2>
                       <ul>
                          <li>Significantly reduces the risk of unauthorized access to your accounts.</li>
                           <li>Provides an added layer of protection against phishing attacks.</li>
                            <li>Protects your privacy and sensitive information online.</li>
                      </ul>
                   </section>
                  <section className="two-factor-section">
                       <h2 className="two-factor-section-title">Types of 2FA Methods</h2>
                       <ul>
                           <li><strong>Authenticator Apps:</strong> Apps like Google Authenticator, Authy, or Microsoft Authenticator generate time-based codes.</li>
                            <li><strong>SMS Verification:</strong> A code is sent to your phone via SMS. (not as secure as other methods)</li>
                             <li><strong>Email Verification:</strong> A code is sent to your email. (not as secure as other methods)</li>
                            <li><strong>Security Keys:</strong> Physical devices (like YubiKeys) that plug into your computer or phone and are used to verify your identity.</li>
                      </ul>
                  </section>
                <section className="two-factor-section">
                     <h2 className="two-factor-section-title">Resources to Setup 2FA</h2>
                    <p>
                           Here are some resources to help you set up 2FA on common services:
                   </p>
                    <ul>
                         <li><a href="https://support.google.com/accounts/answer/185839" target="_blank" rel="noopener noreferrer">Google Account 2FA</a></li>
                         <li><a href="https://www.microsoft.com/en-us/security/mobile-authenticator-app" target="_blank" rel="noopener noreferrer">Microsoft Account 2FA</a></li>
                         <li><a href="https://www.facebook.com/help/148233965247823" target="_blank" rel="noopener noreferrer">Facebook 2FA</a></li>
                           <li><a href="https://help.twitter.com/en/managing-your-account/two-factor-authentication" target="_blank" rel="noopener noreferrer">Twitter 2FA</a></li>
                    </ul>
                </section>
            </div>
        </div>
    );
}

export default TwoFactorAuthPage;